


import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author ADMIN
 */
public class frmDSSach extends javax.swing.JFrame {

    /**
     * Creates new form frmQLTheLoai
     */
    public frmDSSach() {
        initComponents();
        // can giua cho form
        //this.setSize(1102,519);
        this.setLocationRelativeTo(null);
        setupUI();
    
    }
    
    private void setupUI(){
        // tao vien xam cho khung panel
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(30, 130, 76));
        
        jPanel_Theloaisach.setBorder(panelHeaderBorder);
        tblDanhsach.setSelectionBackground(new Color(217, 237, 191));
        tblDanhsach.setSelectionForeground(Color.white);
        tblDanhsach.setRowHeight(30);
        tblDanhsach.setShowGrid(true);
        tblDanhsach.setBackground(new Color(238, 233, 233));
        // thiet ke cho hang tren dau cua bang
        tblDanhsach.getTableHeader().setBackground(new Color(135, 211, 124));
        tblDanhsach.getTableHeader().setForeground(Color.white);
        tblDanhsach.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 12));
        tblDanhsach.getTableHeader().setOpaque(false);

        tblDanhsach.getTableHeader().repaint();
        //CODE LOI TAM THOI NOTE
        //controllers.Func_Class func = new controllers.Func_Class();
        //func.displayImage(60,60,"/image/DSsach.png", lblTieudeTL );
        lblMinus.setOpaque(true); // Cho phép JLabel có background
        lblMinus.setBackground(new java.awt.Color(30,130,76)); 
        lblSystemIC.setOpaque(true); // Cho phép JLabel có background
        lblSystemIC.setBackground(new java.awt.Color(30,130,76)); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Theloaisach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhsach = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblMasach = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnTim1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblTensach = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTensach1 = new javax.swing.JLabel();
        Ngaydau = new com.toedter.calendar.JDateChooser();
        Ngaycuoi = new com.toedter.calendar.JDateChooser();
        btnTim2 = new javax.swing.JButton();
        Anhbia = new javax.swing.JLabel();
        matg = new javax.swing.JLabel();
        tentg = new javax.swing.JLabel();
        theloai = new javax.swing.JLabel();
        nhaxb = new javax.swing.JLabel();
        gia = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        lblTieude = new javax.swing.JLabel();
        lblSystemIC = new javax.swing.JLabel();
        lblMinus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Theloaisach.setBackground(new java.awt.Color(200, 247, 197));
        jPanel_Theloaisach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDanhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng", "Ngày nhập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhsach.setShowGrid(true);
        jScrollPane1.setViewportView(tblDanhsach);

        jPanel_Theloaisach.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 206, 952, 449));

        lblMasach.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblMasach.setText("Tìm kiếm:");

        txtTimkiem.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Tìm kiếm theo tên hoặc mô tả");

        btnTim1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTim1.setText("Tìm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblMasach, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btnTim1)
                        .addGap(39, 39, 39))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMasach, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim1))
                .addGap(21, 21, 21))
        );

        jPanel_Theloaisach.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 84, -1, -1));

        lblTensach.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblTensach.setText("Từ ngày:");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Tìm kiếm sách theo ngày nhập");

        lblTensach1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblTensach1.setText("Đến ngày:");

        btnTim2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTim2.setText("Tìm");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTensach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ngaydau, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTensach1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ngaycuoi, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(btnTim2)
                        .addGap(22, 22, 22))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTensach1)
                    .addComponent(lblTensach)
                    .addComponent(Ngaydau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ngaycuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim2))
                .addGap(17, 17, 17))
        );

        jPanel_Theloaisach.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 84, -1, 104));

        Anhbia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Anhbia.setText("Ảnh bìa");
        Anhbia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Anhbia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Anhbia.setOpaque(true);
        jPanel_Theloaisach.add(Anhbia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, 154, 190));

        matg.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        matg.setForeground(new java.awt.Color(51, 51, 255));
        matg.setText("Mã tác giả");
        jPanel_Theloaisach.add(matg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 470, 191, -1));

        tentg.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tentg.setForeground(new java.awt.Color(51, 51, 255));
        tentg.setText("Tên tác giả");
        jPanel_Theloaisach.add(tentg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 500, 191, -1));

        theloai.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        theloai.setForeground(new java.awt.Color(51, 51, 255));
        theloai.setText("Thể loại");
        jPanel_Theloaisach.add(theloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 530, 191, -1));

        nhaxb.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        nhaxb.setForeground(new java.awt.Color(51, 51, 255));
        nhaxb.setText("Nhà xuất bản");
        jPanel_Theloaisach.add(nhaxb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 560, 191, -1));

        gia.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        gia.setForeground(new java.awt.Color(51, 51, 255));
        gia.setText("Giá");
        jPanel_Theloaisach.add(gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 590, 191, -1));

        pnlHeader.setBackground(new java.awt.Color(30, 130, 76));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTieude.setBackground(new java.awt.Color(241, 231, 254));
        lblTieude.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTieude.setForeground(new java.awt.Color(255, 255, 255));
        lblTieude.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTieude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/book.png"))); // NOI18N
        lblTieude.setText("    Kho sách");
        lblTieude.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlHeader.add(lblTieude, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 270, 70));

        lblSystemIC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystemIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_close24.png"))); // NOI18N
        lblSystemIC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSystemIC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSystemICMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSystemICMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSystemICMouseExited(evt);
            }
        });
        pnlHeader.add(lblSystemIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 5, 60, 60));

        lblMinus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_minus.png"))); // NOI18N
        lblMinus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinusMouseExited(evt);
            }
        });
        pnlHeader.add(lblMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 5, 60, 60));

        jPanel_Theloaisach.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 70));

        getContentPane().add(jPanel_Theloaisach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSystemICMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSystemICMouseClicked
        // TODO add your handling code here:
        // Dong form
        this.dispose();
    }//GEN-LAST:event_lblSystemICMouseClicked

    private void lblSystemICMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSystemICMouseEntered
        // TODO add your handling code here:
        lblSystemIC.setBackground(new java.awt.Color(255,102,102));
    }//GEN-LAST:event_lblSystemICMouseEntered

    private void lblSystemICMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSystemICMouseExited
        // TODO add your handling code here:
        lblSystemIC.setBackground(new java.awt.Color(30,130,76));
    }//GEN-LAST:event_lblSystemICMouseExited

    private void lblMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinusMouseClicked
        // TODO add your handling code here:
        // Thu nhỏ form lại
        this.setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinusMouseClicked

    private void lblMinusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinusMouseEntered
        // TODO add your handling code here:
        lblMinus.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblMinusMouseEntered

    private void lblMinusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinusMouseExited
        // TODO add your handling code here:
        lblMinus.setBackground(new java.awt.Color(30,130,76));
    }//GEN-LAST:event_lblMinusMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDSSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmDSSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anhbia;
    private com.toedter.calendar.JDateChooser Ngaycuoi;
    private com.toedter.calendar.JDateChooser Ngaydau;
    private javax.swing.JButton btnTim1;
    private javax.swing.JButton btnTim2;
    private javax.swing.JLabel gia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_Theloaisach;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMasach;
    private javax.swing.JLabel lblMinus;
    private javax.swing.JLabel lblSystemIC;
    private javax.swing.JLabel lblTensach;
    private javax.swing.JLabel lblTensach1;
    private javax.swing.JLabel lblTieude;
    private javax.swing.JLabel matg;
    private javax.swing.JLabel nhaxb;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTable tblDanhsach;
    private javax.swing.JLabel tentg;
    private javax.swing.JLabel theloai;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
