


import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;

/**
 *
 * @author ADMIN
 */
public class frmQLNguoiDung extends javax.swing.JFrame {

    /**
     * Creates new form frmQLTheLoai
     */
    public frmQLNguoiDung() {
        
        // Dòng lệnh dưới dùng để khắc phục lỗi mở bảng trong trang chủ
        
        try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            }
        
        initComponents();
        
        // can giua cho form
        
        this.setSize(1102,519);
        this.setLocationRelativeTo(null);
        // tao vien xam cho khung panel
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(30, 130, 76));
        
        jPanel_Theloaisach.setBorder(panelHeaderBorder);
        tblQLNguoidung.setSelectionBackground(new Color(217, 237, 191));
        tblQLNguoidung.setSelectionForeground(Color.white);
        tblQLNguoidung.setRowHeight(30);
        tblQLNguoidung.setShowGrid(true);
        tblQLNguoidung.setBackground(new Color(238, 233, 233));
        // thiet ke cho hang tren dau cua bang
        tblQLNguoidung.getTableHeader().setBackground(new Color(135, 211, 124));
        tblQLNguoidung.getTableHeader().setForeground(Color.white);
        tblQLNguoidung.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 12));
        tblQLNguoidung.getTableHeader().setOpaque(false);

        tblQLNguoidung.getTableHeader().repaint();
        //CODE LOI TAM THOI NOTE
        controllers.Func_Class func = new controllers.Func_Class();
        func.displayImage(60,60,"/image/ic-QLynguoidung.png", lblTieudeTL );
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Theloaisach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLNguoidung = new javax.swing.JTable();
        lblMasach = new javax.swing.JLabel();
        lblTensach = new javax.swing.JLabel();
        lblTacgia = new javax.swing.JLabel();
        lblTheloai = new javax.swing.JLabel();
        lblSoluong = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtTentaikhoan = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblTieudeTL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pwMatkhau = new javax.swing.JPasswordField();
        pwNhaplaimk = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_CloseFormTL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Theloaisach.setBackground(new java.awt.Color(200, 247, 197));
        jPanel_Theloaisach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblQLNguoidung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ tên", "Tên tài khoản", "Mật khẩu", "Quyền hạn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblQLNguoidung.setShowGrid(true);
        jScrollPane1.setViewportView(tblQLNguoidung);

        jPanel_Theloaisach.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 520, -1));

        lblMasach.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblMasach.setText("ID:");
        jPanel_Theloaisach.add(lblMasach, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 24));

        lblTensach.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblTensach.setText("Họ tên:");
        jPanel_Theloaisach.add(lblTensach, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        lblTacgia.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblTacgia.setText("Tên tài khoản:");
        jPanel_Theloaisach.add(lblTacgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        lblTheloai.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblTheloai.setText("Mật khẩu:");
        jPanel_Theloaisach.add(lblTheloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        lblSoluong.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblSoluong.setText("Nhập lại mật khẩu:");
        jPanel_Theloaisach.add(lblSoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        txtID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel_Theloaisach.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 225, -1));

        txtHoten.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel_Theloaisach.add(txtHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 225, -1));

        txtTentaikhoan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel_Theloaisach.add(txtTentaikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 225, -1));

        btnThem.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Theloaisach.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        btnHuy.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnHuy.setText("Hủy bỏ");
        btnHuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Theloaisach.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        lblTieudeTL.setBackground(new java.awt.Color(30, 130, 76));
        lblTieudeTL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTieudeTL.setForeground(new java.awt.Color(255, 255, 255));
        lblTieudeTL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieudeTL.setText("Quản lý người dùng");
        lblTieudeTL.setOpaque(true);
        jPanel_Theloaisach.add(lblTieudeTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 57));

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("Sửa");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Theloaisach.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 86, -1));

        pwMatkhau.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel_Theloaisach.add(pwMatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 152, -1));

        pwNhaplaimk.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel_Theloaisach.add(pwNhaplaimk, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 152, -1));

        jCheckBox1.setBackground(new java.awt.Color(200, 247, 197));
        jCheckBox1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(51, 51, 255));
        jCheckBox1.setText("Đặt làm quản trị viên");
        jCheckBox1.setBorder(null);
        jCheckBox1.setContentAreaFilled(false);
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1.setFocusPainted(false);
        jPanel_Theloaisach.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("* ID không được để trống");
        jPanel_Theloaisach.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("* Họ tên không được để trống");
        jPanel_Theloaisach.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 173, -1));

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("* Tên tài khoản không được để trống");
        jPanel_Theloaisach.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 203, -1));

        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("* Mật khẩu không được để trống");
        jPanel_Theloaisach.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 183, -1));

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("* Mật khẩu không khớp");
        jPanel_Theloaisach.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 160, -1));

        lbl_CloseFormTL.setBackground(new java.awt.Color(30, 130, 76));
        lbl_CloseFormTL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_CloseFormTL.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CloseFormTL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CloseFormTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_close24.png"))); // NOI18N
        lbl_CloseFormTL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_CloseFormTL.setOpaque(true);
        lbl_CloseFormTL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CloseFormTLMouseClicked(evt);
            }
        });
        jPanel_Theloaisach.add(lbl_CloseFormTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 72, 57));

        getContentPane().add(jPanel_Theloaisach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 524));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_CloseFormTLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseFormTLMouseClicked
        // TODO add your handling code here:
        // Dong form the loai sach
        this.dispose();
    }//GEN-LAST:event_lbl_CloseFormTLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQLNguoiDung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel_Theloaisach;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMasach;
    private javax.swing.JLabel lblSoluong;
    private javax.swing.JLabel lblTacgia;
    private javax.swing.JLabel lblTensach;
    private javax.swing.JLabel lblTheloai;
    private javax.swing.JLabel lblTieudeTL;
    private javax.swing.JLabel lbl_CloseFormTL;
    private javax.swing.JPasswordField pwMatkhau;
    private javax.swing.JPasswordField pwNhaplaimk;
    private javax.swing.JTable tblQLNguoidung;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTentaikhoan;
    // End of variables declaration//GEN-END:variables
}
