/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui_library;

/**
 *
 * @author admin
 */
public class frmDangKy extends javax.swing.JFrame {

    /**
     * Creates new form frmDangKy
     */
    public frmDangKy() {
        initComponents();
        // can giua cho form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSignIn = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblReview = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblDPassword = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblUserIc = new javax.swing.JLabel();
        lblPasswordIc = new javax.swing.JLabel();
        lblEmailIc = new javax.swing.JLabel();
        lblPhoneIc = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtDPassword = new javax.swing.JPasswordField();
        btnDangki = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        lblThoat = new javax.swing.JLabel();
        lblPwIc = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        pnlWelcome = new javax.swing.JPanel();
        lblWel = new javax.swing.JLabel();
        lblPic = new javax.swing.JLabel();
        lblCome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(2147, 2147));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSignIn.setBackground(new java.awt.Color(137, 196, 244));
        pnlSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSignIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(40, 67, 135));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Đăng ký thành viên");
        pnlSignIn.add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 72, -1, 48));

        lblReview.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        lblReview.setForeground(new java.awt.Color(75, 119, 190));
        lblReview.setText("Tham gia cộng đồng yêu sách của chúng tôi");
        pnlSignIn.add(lblReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 126, -1, -1));

        lblUsername.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(40, 67, 135));
        lblUsername.setText("Tên người dùng:");
        pnlSignIn.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 182, 298, 32));

        lblDPassword.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblDPassword.setForeground(new java.awt.Color(40, 67, 135));
        lblDPassword.setText("Nhập lại mật khẩu:");
        pnlSignIn.add(lblDPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 298, 32));

        lblEmail.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(40, 67, 135));
        lblEmail.setText("Email:");
        pnlSignIn.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 428, 298, 32));

        lblPhone.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(40, 67, 135));
        lblPhone.setText("Số điện thoại:");
        pnlSignIn.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 508, 298, 32));

        lblUserIc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_Account.png"))); // NOI18N
        pnlSignIn.add(lblUserIc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        lblPasswordIc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_Baomat.png"))); // NOI18N
        pnlSignIn.add(lblPasswordIc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        lblEmailIc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmailIc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_Secured_Letter.png"))); // NOI18N
        pnlSignIn.add(lblEmailIc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, 42));

        lblPhoneIc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoneIc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_dienthoai.png"))); // NOI18N
        pnlSignIn.add(lblPhoneIc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 50, 45));

        txtUserName.setBackground(new java.awt.Color(137, 196, 244));
        txtUserName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(40, 67, 135));
        txtUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(40, 67, 135)));
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });
        pnlSignIn.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 216, 298, 32));

        txtEmail.setBackground(new java.awt.Color(137, 196, 244));
        txtEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(40, 67, 135));
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(40, 67, 135)));
        pnlSignIn.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 298, 32));

        txtPhone.setBackground(new java.awt.Color(137, 196, 244));
        txtPhone.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(40, 67, 135));
        txtPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(40, 67, 135)));
        pnlSignIn.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 298, 32));

        txtDPassword.setBackground(new java.awt.Color(137, 196, 244));
        txtDPassword.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtDPassword.setForeground(new java.awt.Color(40, 67, 135));
        txtDPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(40, 67, 135)));
        pnlSignIn.add(txtDPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 298, 32));

        btnDangki.setBackground(new java.awt.Color(255, 102, 102));
        btnDangki.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnDangki.setForeground(new java.awt.Color(255, 255, 255));
        btnDangki.setText("Đăng ký");
        btnDangki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSignIn.add(btnDangki, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, 193, 44));

        lblResult.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblResult.setForeground(new java.awt.Color(68, 108, 179));
        lblResult.setText("Bạn đã có tài khoản?");
        pnlSignIn.add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 140, 24));

        lblThoat.setBackground(new java.awt.Color(255, 255, 255));
        lblThoat.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(68, 108, 179));
        lblThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_exit_color.png"))); // NOI18N
        lblThoat.setText("Thoát");
        lblThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        pnlSignIn.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, 98, 50));

        lblPwIc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_Baomat.png"))); // NOI18N
        pnlSignIn.add(lblPwIc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        lblPassword.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(40, 67, 135));
        lblPassword.setText("Mật khẩu:");
        pnlSignIn.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 268, 298, 30));

        txtPassword.setBackground(new java.awt.Color(137, 196, 244));
        txtPassword.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(40, 67, 135));
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(40, 67, 135)));
        pnlSignIn.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 298, 298, 32));

        btnDangNhap.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(68, 108, 179));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 102, 102)));
        btnDangNhap.setContentAreaFilled(false);
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseClicked(evt);
            }
        });
        pnlSignIn.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 670, -1, 24));

        getContentPane().add(pnlSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 484, 730));

        pnlWelcome.setBackground(new java.awt.Color(255, 255, 255));
        pnlWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWel.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblWel.setForeground(new java.awt.Color(40, 67, 135));
        lblWel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWel.setText("CHÀO MỪNG BẠN");
        pnlWelcome.add(lblWel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 52));

        lblPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/signup-library.png"))); // NOI18N
        pnlWelcome.add(lblPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 191, 510, 510));

        lblCome.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblCome.setForeground(new java.awt.Color(40, 67, 135));
        lblCome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCome.setText(" ĐẾN VỚI THẾ GIỚI SÁCH");
        pnlWelcome.add(lblCome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 295, 47));

        getContentPane().add(pnlWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusGained
        // TODO add your handling code here:
        if (txtUserName.getText().equals("Nhập tên của bạn")) {
            txtUserName.setText("");  // Xóa placeholder khi người dùng bắt đầu nhập
        }
    }//GEN-LAST:event_txtUserNameFocusGained

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
        // TODO add your handling code here:
        if (txtUserName.getText().equals("")) {
            txtUserName.setText("Nhập tên của bạn");  // Đặt lại placeholder nếu trường còn trống
        }
    }//GEN-LAST:event_txtUserNameFocusLost

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        // TODO add your handling code here:
        // Dong form 
        System.exit(0);
    }//GEN-LAST:event_lblThoatMouseClicked

    private void btnDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseClicked
        // TODO add your handling code here:
        frmDangnhap login = new frmDangnhap();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangNhapMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnDangki;
    private javax.swing.JLabel lblCome;
    private javax.swing.JLabel lblDPassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailIc;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordIc;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneIc;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblPwIc;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblReview;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblUserIc;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWel;
    private javax.swing.JPanel pnlSignIn;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JPasswordField txtDPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
