/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui_library;
import controllers.NguoiDungController;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author ADMIN
 */
public class frmDangnhap extends javax.swing.JFrame {

    /**
     * Creates new form frmDangnhap
     */
    public frmDangnhap() {
        initComponents();
        // can giua form
        this.setLocationRelativeTo(null);
        
        // Hiển thị hình ảnh logo
        displayImage();
        
        // Thêm placeholder cho từng JTextField
        addPlaceholder(txtTaikhoanDN, "Nhập tài khoản");
        addPlaceholder(txtMatkhau, "**************");
         // Cài đặt biểu tượng show/hide mật khẩu
        lblShowMK.setVisible(true); // Hiển thị biểu tượng mở mắt ban đầu
        lblHideMK.setVisible(false); // Ẩn biểu tượng đóng mắt ban đầu
        // Đặt ký tự ẩn mật khẩu mặc định
        txtMatkhau.setEchoChar('*');
        
        //set thong bao
        lblWtkExist.setVisible(false);
        lblWmkExist.setVisible(false);
        lblWdtg.setVisible(false);
        lblWtk.setVisible(false);
        lblWmk.setVisible(false);
        
    }
    
    // Tao ham hien thi hinh anh trong jlabel2
    public final void displayImage() {
        // Lấy ảnh từ thư mục image
        URL imgUrl = getClass().getResource("/image/library-2.png");
        if (imgUrl != null) {
            ImageIcon imgIco = new ImageIcon(imgUrl);
            // Thay đổi kích thước ảnh cho phù hợp với JLabel
            Image image = imgIco.getImage().getScaledInstance(lbl_logo.getWidth(), lbl_logo.getHeight(), Image.SCALE_SMOOTH);
            // Đặt ảnh vào JLabel
            lbl_logo.setIcon(new ImageIcon(image));
        }
    }
    
    private void addPlaceholder(JTextField textField, String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(Color.GRAY); // Gợi ý hiển thị màu nhạt

        textField.addFocusListener(new java.awt.event.FocusListener() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            if (textField.getText().equals(placeholder)) {
                textField.setText("");
                textField.setForeground(Color.BLACK); // Đổi về màu bình thường khi người dùng nhập
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            if (textField.getText().isEmpty()) {
                textField.setText(placeholder);
                textField.setForeground(Color.GRAY); // Đổi về màu placeholder khi trống
            }
        }
        });
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTaikhoanDN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMatkhau = new javax.swing.JPasswordField();
        cmbTypeUser = new javax.swing.JComboBox<>();
        btnDangnhap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDangki = new javax.swing.JButton();
        lblWdtg = new javax.swing.JLabel();
        lblShowMK = new javax.swing.JLabel();
        lblHideMK = new javax.swing.JLabel();
        lblWtkExist = new javax.swing.JLabel();
        lblWmkExist = new javax.swing.JLabel();
        lblWtk = new javax.swing.JLabel();
        lblWmk = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblMinFrm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(255, 153, 0)));
        lbl_logo.setName(""); // NOI18N
        getContentPane().add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 480, 190));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(255, 153, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tài Khoản:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 103, 30));

        txtTaikhoanDN.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtTaikhoanDN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTaikhoanDNKeyReleased(evt);
            }
        });
        jPanel1.add(txtTaikhoanDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 40, 320, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mật khẩu:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 99, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Bạn là ai ?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 123, 30));

        txtMatkhau.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtMatkhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatkhauKeyReleased(evt);
            }
        });
        jPanel1.add(txtMatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 120, 320, 30));

        cmbTypeUser.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        cmbTypeUser.setForeground(new java.awt.Color(51, 51, 255));
        cmbTypeUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        cmbTypeUser.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), null));
        cmbTypeUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbTypeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeUserActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTypeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 200, 320, 30));

        btnDangnhap.setBackground(new java.awt.Color(255, 102, 102));
        btnDangnhap.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnDangnhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangnhap.setText("Đăng nhập");
        btnDangnhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangnhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic-key.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 30, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic-BlackUser.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 30, 30));

        btnDangki.setFont(new java.awt.Font("Roboto", 2, 16)); // NOI18N
        btnDangki.setForeground(new java.awt.Color(255, 102, 102));
        btnDangki.setText("Bạn chưa có tài khoản ? Đăng kí");
        btnDangki.setContentAreaFilled(false);
        btnDangki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangki.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDangki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangkiActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangki, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 280, 30));

        lblWdtg.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblWdtg.setForeground(new java.awt.Color(255, 51, 51));
        lblWdtg.setText("* Hãy chọn đúng đối tượng");
        jPanel1.add(lblWdtg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 280, -1));

        lblShowMK.setBackground(new java.awt.Color(255, 102, 102));
        lblShowMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_eyeopen.png"))); // NOI18N
        lblShowMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowMKMouseClicked(evt);
            }
        });
        jPanel1.add(lblShowMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 32, 30));

        lblHideMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_eyeclose.png"))); // NOI18N
        lblHideMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHideMKMouseClicked(evt);
            }
        });
        jPanel1.add(lblHideMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 32, 30));

        lblWtkExist.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblWtkExist.setForeground(new java.awt.Color(255, 51, 51));
        lblWtkExist.setText("* Tài khoản không tồn tại");
        jPanel1.add(lblWtkExist, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 280, -1));

        lblWmkExist.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblWmkExist.setForeground(new java.awt.Color(255, 51, 51));
        lblWmkExist.setText("* Mật khẩu không khớp");
        jPanel1.add(lblWmkExist, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 280, -1));

        lblWtk.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblWtk.setForeground(new java.awt.Color(255, 51, 51));
        lblWtk.setText("* Tài khoản không được để trống");
        jPanel1.add(lblWtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 280, -1));

        lblWmk.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblWmk.setForeground(new java.awt.Color(255, 51, 51));
        lblWmk.setText("* Mật khẩu không được để trống");
        jPanel1.add(lblWmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 280, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 480, 375));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(255, 153, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Đăng nhập");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 210, 60));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_close.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel2.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 20, 20));

        lblMinFrm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinFrm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_zoom24.png"))); // NOI18N
        lblMinFrm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinFrmMouseClicked(evt);
            }
        });
        jPanel2.add(lblMinFrm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 20, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTypeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeUserActionPerformed
        // TODO add your handling code here:
        String loaiNguoiDung = cmbTypeUser.getSelectedItem().toString();
        
        // Kiểm tra loại người dùng và thực hiện các hành động tương ứng
        switch (loaiNguoiDung) {
            case "Admin" -> System.out.println("Ban da chon Quan tri vien");
            case "User" -> System.out.println("Ban da chon doc gia");
            default -> System.out.println("Vui long chon loai nguoi dung hop le");
        }
    }//GEN-LAST:event_cmbTypeUserActionPerformed

    private void btnDangkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangkiActionPerformed
        // TODO add your handling code here:
        frmDangKy register = new frmDangKy();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangkiActionPerformed

   
    
    private void btnDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangnhapActionPerformed
         try {
            // Lấy dữ liệu từ giao diện
            String taikhoan = txtTaikhoanDN.getText().trim();
            String matkhau = new String(txtMatkhau.getPassword()).trim();
            String loainguoidung = cmbTypeUser.getSelectedItem().toString();
        
            /*
            // Kiểm tra nếu tài khoản chưa được nhập
            if (taikhoan.isEmpty()) {
                lblWtk.setVisible(true);  // Hiển thị thông báo lỗi tài khoản
                return;
            }
           
            // Kiểm tra nếu mật khẩu chưa được nhập
            if (matkhau.isEmpty()) {
                lblWmk.setVisible(true);  // Hiển thị thông báo lỗi mật khẩu
                return;
            }
 */
            // Kiểm tra nếu loại người dùng chưa được chọn
            if (loainguoidung.equals("Chọn đối tượng")) {
                lblWdtg.setVisible(true);  // Hiển thị thông báo lỗi loại người dùng
                return;
            }

            // Gọi phương thức kiểm tra đăng nhập từ controller
            NguoiDungController nguoiDungCtrl = new NguoiDungController();

            // Kiểm tra đăng nhập
            boolean isSuccess = nguoiDungCtrl.kiemTraDangNhap(taikhoan, matkhau, loainguoidung);

            // Nếu đăng nhập thành công, kiểm tra thêm loại người dùng
            if (isSuccess) {
                // Kiểm tra xem loại người dùng có khớp với tài khoản đã đăng nhập không
                boolean isRoleValid = nguoiDungCtrl.kiemTraLoaiNguoiDung(taikhoan, loainguoidung);

                if (isRoleValid) {
                    // Đăng nhập thành công và loại người dùng đúng
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                    // Chuyển đến màn hình chính
                    frmTrangchu home = new frmTrangchu();
                    home.setVisible(true);
                    // Đóng form đăng nhập
                    this.dispose();     
                } else {
                    // Nếu loại người dùng không đúng
                    lblWdtg.setVisible(true);  // Hiển thị thông báo loại người dùng không khớp
                }
            } else {
                // Đăng nhập thất bại, kiểm tra nguyên nhân
                if (!nguoiDungCtrl.isValidAccount(taikhoan)) {
                    if (taikhoan.isEmpty()) {
                        lblWtk.setVisible(true);  

                    } else {
                        lblWtk.setVisible(false);  
                        lblWtkExist.setVisible(true);  // Hiển thị thông báo tài khoản không tồn tại
                        lblWdtg.setVisible(false);  // Ẩn thông báo loại người dùng không hợp lệ
                        lblWmkExist.setVisible(false);  // Ẩn thông báo mật khẩu sai
                    }
                    
                } else if (!nguoiDungCtrl.isValidPassword(matkhau, taikhoan)) {
                    lblWmkExist.setVisible(true);  // Hiển thị thông báo mật khẩu sai
                    lblWtkExist.setVisible(false);  // Ẩn thông báo tài khoản không tồn tại
                    lblWdtg.setVisible(false);  // Ẩn thông báo loại người dùng không hợp lệ
                } else {
                    lblWdtg.setVisible(false);
                    lblWtkExist.setVisible(false);
                    lblWmkExist.setVisible(false);
                    JOptionPane.showMessageDialog(this, "Đăng nhập thất bại! Vui lòng kiểm tra lại thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }         
        } catch (SQLException ex) {
            // Xử lý lỗi cơ sở dữ liệu
            Logger.getLogger(frmDangnhap.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Lỗi hệ thống! Vui lòng thử lại sau.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDangnhapActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinFrmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinFrmMouseClicked
        // TODO add your handling code here:
        // Thu nhỏ form lại
        this.setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinFrmMouseClicked

    private void lblShowMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowMKMouseClicked
        // TODO add your handling code here:
        txtMatkhau.setEchoChar((char) 0); // Hiển thị mật khẩu
        lblShowMK.setVisible(false); // Ẩn biểu tượng mở mắt
        lblHideMK.setVisible(true); // Hiển thị biểu tượng đóng mắt
    }//GEN-LAST:event_lblShowMKMouseClicked

    private void lblHideMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHideMKMouseClicked
        // TODO add your handling code here:
        // Ẩn mật khẩu (trở về dạng ***)
        txtMatkhau.setEchoChar('*'); // Ẩn mật khẩu (dạng ***)
        lblShowMK.setVisible(true); // Hiển thị biểu tượng mở mắt
        lblHideMK.setVisible(false); // Ẩn biểu tượng đóng mắt
        
    }//GEN-LAST:event_lblHideMKMouseClicked

    private void txtTaikhoanDNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaikhoanDNKeyReleased
        // TODO add your handling code here:
        String taikhoan = txtTaikhoanDN.getText().trim();
        // Kiểm tra điều kiện tên tài khoản 
        // Nếu tài khoản không rỗng, ẩn lblWtk
        if (!taikhoan.isEmpty()) {
            lblWtk.setVisible(false);  // Ẩn lblWtk nếu tài khoản đã được nhập
            
        } else {
            lblWtk.setVisible(true);   // Hiển thị lblWtk nếu tài khoản vẫn rỗng
            lblWtkExist.setVisible(false);
        }
        
    }//GEN-LAST:event_txtTaikhoanDNKeyReleased

    private void txtMatkhauKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatkhauKeyReleased
        // TODO add your handling code here:
        String taikhoan = txtTaikhoanDN.getText().trim();
        String matkhau = new String(txtMatkhau.getPassword()).trim();
        
        // Nếu tài khoản không rỗng, ẩn lblWtk
        if (!matkhau.isEmpty()) {
            lblWmk.setVisible(false);  // Ẩn lblWtk nếu tài khoản đã được nhập
            
        } else {
            lblWmk.setVisible(true);   // Hiển thị lblWtk nếu tài khoản vẫn rỗng
            lblWmkExist.setVisible(false);
        }
        
        
    }//GEN-LAST:event_txtMatkhauKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    //javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmDangnhap().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangki;
    private javax.swing.JButton btnDangnhap;
    private javax.swing.JComboBox<String> cmbTypeUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblHideMK;
    private javax.swing.JLabel lblMinFrm;
    private javax.swing.JLabel lblShowMK;
    private javax.swing.JLabel lblWdtg;
    private javax.swing.JLabel lblWmk;
    private javax.swing.JLabel lblWmkExist;
    private javax.swing.JLabel lblWtk;
    private javax.swing.JLabel lblWtkExist;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JPasswordField txtMatkhau;
    private javax.swing.JTextField txtTaikhoanDN;
    // End of variables declaration//GEN-END:variables
}
