/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui_library;

import controllers.SachController;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import models.SachModel;

/**
 *
 * @author ADMIN
 */
public class frmQLSach extends javax.swing.JFrame {

    /**
     * Creates new form frmQLTheLoai
     * @throws java.sql.SQLException
     */
    public frmQLSach() throws SQLException {
        
        // Dòng lệnh dưới dùng để khắc phục lỗi mở bảng trong trang chủ
        
        try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            }
        
        initComponents();
        
        // can giua cho form
        
        this.setSize(1418,725);
        this.setLocationRelativeTo(null);
        // tao vien xam cho khung panel
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(238, 180, 34));
        
        jPanel_Theloaisach.setBorder(panelHeaderBorder);
        tblQuanlysach.setSelectionBackground(new Color(255, 222, 149));
        tblQuanlysach.setSelectionForeground(Color.white);
        tblQuanlysach.setRowHeight(30);
        tblQuanlysach.setShowGrid(true);
        tblQuanlysach.setBackground(new Color(238, 233, 233));
        // thiet ke cho hang tren dau cua bang
        tblQuanlysach.getTableHeader().setBackground(new Color(242, 120, 75)); 
        tblQuanlysach.getTableHeader().setForeground(Color.white);
        tblQuanlysach.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 12));
        tblQuanlysach.getTableHeader().setOpaque(false);

        tblQuanlysach.getTableHeader().repaint();
       
        tblQuanlysach.getColumnModel().getColumn(0).setPreferredWidth(20);
        tblQuanlysach.getColumnModel().getColumn(4).setPreferredWidth(40);
        tblQuanlysach.getColumnModel().getColumn(5).setPreferredWidth(40);
        controllers.Func_Class func = new controllers.Func_Class();
        func.displayImage(60,60,"/image/books-1977235.png", lblTieudeTL );
        
        //Goi phuong thuc
        hienthisach();
        hienthiDStheloai();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Theloaisach = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_CloseFormTL = new javax.swing.JLabel();
        lblMasach = new javax.swing.JLabel();
        lblTensach = new javax.swing.JLabel();
        lblTacgia = new javax.swing.JLabel();
        lblTheloai = new javax.swing.JLabel();
        lblSoluong = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        txtMasach = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        txtTenTacGia = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaQLsach = new javax.swing.JTextArea();
        lblAnhQLsach = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTieudeTL = new javax.swing.JLabel();
        lblChonanhbia = new javax.swing.JLabel();
        cmbTheloai = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNgaynhap = new javax.swing.JTextField();
        txtNhaxuatban = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIDTacgia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuanlysach = new javax.swing.JTable();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel_Theloaisach.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Theloaisach.setPreferredSize(new java.awt.Dimension(1418, 725));
        jPanel_Theloaisach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_CloseFormTL.setBackground(new java.awt.Color(238, 180, 34));
        lbl_CloseFormTL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_CloseFormTL.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CloseFormTL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CloseFormTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_close24.png"))); // NOI18N
        lbl_CloseFormTL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_CloseFormTL.setOpaque(true);
        lbl_CloseFormTL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CloseFormTLMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_CloseFormTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 72, 57));

        jPanel_Theloaisach.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1344, 0, 72, -1));

        lblMasach.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblMasach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMasach.setText("ID sách:   ");
        jPanel_Theloaisach.add(lblMasach, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 100, 145, 30));

        lblTensach.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTensach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTensach.setText("Tên sách:   ");
        jPanel_Theloaisach.add(lblTensach, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 145, 145, 30));

        lblTacgia.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTacgia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTacgia.setText("Tác giả:   ");
        jPanel_Theloaisach.add(lblTacgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 235, 145, 30));

        lblTheloai.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTheloai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTheloai.setText("Thể loại:   ");
        jPanel_Theloaisach.add(lblTheloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 280, 145, 30));

        lblSoluong.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblSoluong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSoluong.setText("Số Lượng:   ");
        jPanel_Theloaisach.add(lblSoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 325, 145, 30));

        lblGia.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblGia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGia.setText("Giá:   ");
        jPanel_Theloaisach.add(lblGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 145, 30));

        txtMasach.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtMasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMasachActionPerformed(evt);
            }
        });
        jPanel_Theloaisach.add(txtMasach, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 220, 30));

        txtSoLuong.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jPanel_Theloaisach.add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 325, 220, 30));

        txtTenSach.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jPanel_Theloaisach.add(txtTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 145, 220, 30));

        txtTenTacGia.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jPanel_Theloaisach.add(txtTenTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 235, 220, 30));

        txtGia.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jPanel_Theloaisach.add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 220, 30));

        txtAreaQLsach.setColumns(20);
        txtAreaQLsach.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtAreaQLsach.setRows(5);
        jScrollPane2.setViewportView(txtAreaQLsach);

        jPanel_Theloaisach.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 580, 163));

        lblAnhQLsach.setBackground(new java.awt.Color(255, 102, 51));
        lblAnhQLsach.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAnhQLsach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnhQLsach.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblAnhQLsach.setOpaque(true);
        jPanel_Theloaisach.add(lblAnhQLsach, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 172, 232));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Mô tả:   ");
        jPanel_Theloaisach.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 145, 30));

        lblTieudeTL.setBackground(new java.awt.Color(238, 180, 34));
        lblTieudeTL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTieudeTL.setForeground(new java.awt.Color(255, 255, 255));
        lblTieudeTL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieudeTL.setText("Quản lý sách");
        lblTieudeTL.setOpaque(true);
        jPanel_Theloaisach.add(lblTieudeTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1344, 57));

        lblChonanhbia.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        lblChonanhbia.setForeground(new java.awt.Color(51, 51, 255));
        lblChonanhbia.setText("Chọn ảnh bìa");
        lblChonanhbia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblChonanhbia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChonanhbiaMouseClicked(evt);
            }
        });
        jPanel_Theloaisach.add(lblChonanhbia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 103, -1));

        cmbTheloai.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cmbTheloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTheloaiActionPerformed(evt);
            }
        });
        jPanel_Theloaisach.add(cmbTheloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 220, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Ngày nhập:   ");
        jPanel_Theloaisach.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 145, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nhà xuất bản:   ");
        jPanel_Theloaisach.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 415, 165, 30));

        txtNgaynhap.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jPanel_Theloaisach.add(txtNgaynhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 220, 30));

        txtNhaxuatban.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jPanel_Theloaisach.add(txtNhaxuatban, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 415, 220, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("ID tác giả:   ");
        jPanel_Theloaisach.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 190, 145, 30));

        txtIDTacgia.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtIDTacgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDTacgiaActionPerformed(evt);
            }
        });
        jPanel_Theloaisach.add(txtIDTacgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 220, 30));

        tblQuanlysach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Tác giả", "Thể loại", "Số lượng", "Giá", "Ngày nhập", "Nhà xuất bản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblQuanlysach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblQuanlysach.setGridColor(new java.awt.Color(255, 102, 51));
        tblQuanlysach.setShowGrid(true);
        tblQuanlysach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanlysachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuanlysach);

        jPanel_Theloaisach.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 742, 452));

        btnLuu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel_Theloaisach.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 620, -1, -1));

        btnXoa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel_Theloaisach.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 620, -1, -1));

        btnSua.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel_Theloaisach.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Bảng thông tin sách");
        jPanel_Theloaisach.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 245, -1));

        btnThem.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel_Theloaisach.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 620, -1, -1));

        btnHuy.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnHuy.setText("Hủy bỏ");
        btnHuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Theloaisach.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 620, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel_Theloaisach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Theloaisach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_CloseFormTLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseFormTLMouseClicked
        // TODO add your handling code here:
        // Dong form the loai sach
        this.dispose();
    }//GEN-LAST:event_lbl_CloseFormTLMouseClicked

    private void tblQuanlysachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanlysachMouseClicked
        // TODO add your handling code here:
         int selectedRow = tblQuanlysach.getSelectedRow(); 
        if (selectedRow >= 0) {
            try {
                // Lấy model của bảng để truy xuất giá trị
                DefaultTableModel model = (DefaultTableModel) tblQuanlysach.getModel();

                // Lấy ID sách từ cột đầu tiên
                int idSach = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());

                // Lấy danh sách tất cả sách từ controller
                SachController sachCtrl = new SachController();
                List<SachModel> sachList = sachCtrl.getAllSach();

                // Tìm sách theo ID sách
                SachModel sach = null;
                for (SachModel s : sachList) {
                    if (s.getIdSach() == idSach) {
                        sach = s;
                        break;
                    }
                }

                if (sach != null) {
                    // Hiển thị thông tin vào các TextField
                    txtMasach.setText(String.valueOf(sach.getIdSach())); // ID sách
                    txtTenSach.setText(sach.getTenSach()); // Tên sách

                    // Hiển thị ID tác giả từ SachModel
                    txtIDTacgia.setText(String.valueOf(sach.getIdTacGia())); // ID tác giả từ SachModel

                    txtTenTacGia.setText(sach.getTenTacGia()); // Tên tác giả
                    txtSoLuong.setText(String.valueOf(sach.getSoLuong())); // Số lượng
                    txtGia.setText(String.valueOf(sach.getGiaSach())); // Giá sách
                    txtNgaynhap.setText(sach.getNgayNhan()); // Ngày nhận
                    txtNhaxuatban.setText(sach.getNhaXuatBan()); // Nhà xuất bản

                    // Lấy mô tả sách từ SachModel
                    txtAreaQLsach.setText(sach.getMoTa()); // Hiển thị mô tả vào TextArea

                    // Hiển thị thể loại trong ComboBox
                    cmbTheloai.setSelectedItem(sach.getTenTheLoai()); // Thể loại từ SachModel
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmQLSach.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tblQuanlysachMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtMasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMasachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMasachActionPerformed

    private void txtIDTacgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDTacgiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDTacgiaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblQuanlysach.getSelectedRow(); // Lấy hàng được chọn
        if (selectedRow >= 0) {
            try {
                // Lấy thông tin từ các trường dữ liệu
                int idSach = Integer.parseInt(tblQuanlysach.getValueAt(selectedRow, 0).toString());
                String tensach = txtTenSach.getText().trim(); // Tên sách
                if (tensach.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Tên sách không được để trống.");
                    return;
                }

                // Lấy ID tác giả từ đối tượng SachModel đã được chọn
                SachController sachCtrl = new SachController();
                SachModel sach = sachCtrl.getSachById(idSach); // Giả sử bạn có phương thức getSachById để tìm sách theo ID
                int idTacgia = (sach != null) ? sach.getIdTacGia() : -1; // Lấy ID tác giả

                int idTheloai = cmbTheloai.getSelectedIndex() + 1; // Lấy ID thể loại từ comboBox
                String nhaxuatban = txtNhaxuatban.getText().trim(); // Nhà xuất bản
                if (nhaxuatban.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Nhà xuất bản không được để trống.");
                    return;
                }

                double giasach = Double.parseDouble(txtGia.getText().trim()); // Giá sách
//                if (giasach <= 0) {
//                    JOptionPane.showMessageDialog(this, "Giá sách phải lớn hơn 0.");
//                    return;
//                }

                int soluong = Integer.parseInt(txtSoLuong.getText().trim()); // Số lượng
                String ngaynhan = txtNgaynhap.getText().trim(); // Ngày nhận
                String mota = txtAreaQLsach.getText().trim(); // Mô tả sách
                String imagePath = "src\\image" + idSach  + ".jpg"; // Đường dẫn ảnh tương ứng

                // In ra đường dẫn ảnh
            System.out.println("Đường dẫn ảnh là: " + imagePath); // In đường dẫn ảnh ra console
            JOptionPane.showMessageDialog(this, "Đường dẫn ảnh: " + imagePath); 
                // Kiểm tra nếu ảnh tồn tại không
                File imageFile = new File(imagePath);
                if (!imageFile.exists()) {
                    JOptionPane.showMessageDialog(this, "Ảnh bìa không tồn tại.");
                    return;
                }

                // Tạo đối tượng SachModel
                SachModel updatedSach = new SachModel(idSach, tensach, idTacgia, idTheloai, nhaxuatban, giasach, soluong, ngaynhan, mota, imagePath);

                // Cập nhật thông tin
                SachController sachController = new SachController();
                boolean isUpdated = sachController.updateSach(updatedSach, imagePath);

                if (isUpdated) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!");
                    hienthisach(); // Tải lại dữ liệu lên bảng
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi cập nhật!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sách từ bảng để chỉnh sửa.");
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void lblChonanhbiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChonanhbiaMouseClicked
        // TODO add your handling code here:
        // Mở hộp thoại chọn file ảnh
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn ảnh bìa");  // Tiêu đề hộp thoại
        fileChooser.setFileFilter(new FileNameExtensionFilter("Hình ảnh", "jpg", "png", "jpeg"));  // Bộ lọc tệp ảnh

        int returnValue = fileChooser.showOpenDialog(this);  // Hiển thị hộp thoại chọn file
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();  // Lấy tệp ảnh được chọn

            // Đọc và hiển thị ảnh lên Label
            ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());  // Tạo đối tượng ImageIcon từ tệp ảnh
            Image image = imageIcon.getImage().getScaledInstance(lblAnhQLsach.getWidth(), lblAnhQLsach.getHeight(), Image.SCALE_SMOOTH);  // Tỉ lệ ảnh vừa vặn với Label
            lblAnhQLsach.setIcon(new ImageIcon(image));  // Đặt ảnh vào Label

            // Cập nhật đường dẫn ảnh để sử dụng khi lưu vào cơ sở dữ liệu
            // (Đảm bảo rằng đường dẫn này sẽ được lưu vào cơ sở dữ liệu hoặc được sử dụng trong quá trình cập nhật sách)
            String imagePath = selectedFile.getAbsolutePath();

            // Lưu đường dẫn ảnh vào biến tạm thời để lưu vào SQL sau này
            // (Có thể là thuộc tính của đối tượng sach, hoặc trong đối tượng `SachModel`)
            // Ví dụ:
            // sach.setImagePath(imagePath); // Gán đường dẫn ảnh vào đối tượng SachModel nếu cần
        }
    }//GEN-LAST:event_lblChonanhbiaMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblQuanlysach.getSelectedRow(); // Lấy hàng được chọn từ bảng
        if (selectedRow >= 0) {
            try {
                // Cho phép chỉnh sửa các trường
                txtTenSach.setEnabled(true);
                txtIDTacgia.setEnabled(true);
                txtTenTacGia.setEnabled(true);
                txtSoLuong.setEnabled(true);
                txtGia.setEnabled(true);
                txtNgaynhap.setEnabled(true);
                txtNhaxuatban.setEnabled(true);
                txtAreaQLsach.setEnabled(true);
                cmbTheloai.setEnabled(true);
                lblChonanhbia.setEnabled(true); // Cho phép chọn ảnh mới

                // Thông báo người dùng cần lưu lại thay đổi sau khi chỉnh sửa
                JOptionPane.showMessageDialog(this, 
                    "Bạn có thể chỉnh sửa thông tin. Nhấn nút Lưu để lưu thay đổi.",
                    "Chỉnh sửa",
                    JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, 
                    "Đã xảy ra lỗi khi chuẩn bị chỉnh sửa!",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, 
                "Vui lòng chọn một sách từ bảng để chỉnh sửa.",
                "Thông báo",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btnThemActionPerformed

    private void cmbTheloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTheloaiActionPerformed
        // TODO add your handling code here:
        try {
         SachController sachController = new SachController();
         String tenTheLoai = (String) cmbTheloai.getSelectedItem(); // Lấy tên thể loại từ combo box
         int idTheLoai = sachController.getIdTheLoaiFromName(tenTheLoai);
         System.out.println("ID thể loại: " + idTheLoai);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cmbTheloaiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        // Xóa nội dung của các JTextField
        txtTenSach.setText(""); // Xóa tên sách
        txtMasach.setText("");
        txtIDTacgia.setText("");
        txtTenTacGia.setText("");
        txtNhaxuatban.setText(""); // Xóa nhà xuất bản
        txtGia.setText(""); // Xóa giá sách
        txtSoLuong.setText(""); // Xóa số lượng
        txtNgaynhap.setText(""); // Xóa ngày nhập
        
        // Xóa nội dung của JTextArea
        txtAreaQLsach.setText("");

        // Đặt lại lựa chọn trong JComboBox về mặc định (chỉ số 0)
        cmbTheloai.setSelectedIndex(-1);

        // Đặt lại hình ảnh mặc định (nếu có JLabel để hiển thị ảnh)
        lblAnhQLsach.setIcon(null);

        // Hiển thị thông báo nếu cần
        JOptionPane.showMessageDialog(this, "Đã xóa toàn bộ dữ liệu.");
    }//GEN-LAST:event_btnXoaActionPerformed
        private void hienthiDStheloai() {
        try {
            SachController sachController = new SachController();
            List<String> theLoaiList = sachController.getAllTheLoai();

            // Xóa dữ liệu cũ trong combobox
            cmbTheloai.removeAllItems();

            // Thêm dữ liệu mới vào combobox
            for (String theLoai : theLoaiList) {
                cmbTheloai.addItem(theLoai);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private void hienthisach() throws SQLException{
        SachController sachController = new SachController();
        List<SachModel> list = sachController.getAllSach();
        DefaultTableModel model = (DefaultTableModel) tblQuanlysach.getModel();
        // Xoa du lieu cu
        model.setRowCount(0);
        // Them du lieu moi
        for(SachModel sach : list){
            model.addRow(new Object[]{
                sach.getIdSach(),
                sach.getTenSach(),
                sach.getTenTacGia(),
                sach.getTenTheLoai(),
                sach.getSoLuong(),
                sach.getGiaSach(),
                sach.getNgayNhan(),
                sach.getNhaXuatBan(),
                sach.getMoTa()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new frmQLSach().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(frmQLSach.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cmbTheloai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Theloaisach;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnhQLsach;
    private javax.swing.JLabel lblChonanhbia;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblMasach;
    private javax.swing.JLabel lblSoluong;
    private javax.swing.JLabel lblTacgia;
    private javax.swing.JLabel lblTensach;
    private javax.swing.JLabel lblTheloai;
    private javax.swing.JLabel lblTieudeTL;
    private javax.swing.JLabel lbl_CloseFormTL;
    private javax.swing.JTable tblQuanlysach;
    private javax.swing.JTextArea txtAreaQLsach;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtIDTacgia;
    private javax.swing.JTextField txtMasach;
    private javax.swing.JTextField txtNgaynhap;
    private javax.swing.JTextField txtNhaxuatban;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTenTacGia;
    // End of variables declaration//GEN-END:variables
}
