/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui_library;

/**
 *
 * @author admin
 */
public class frmTrangchu extends javax.swing.JFrame {

    /**
     * Creates new form frmTrangchu
     */
    public frmTrangchu() {
        initComponents();
        // can giua cho form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblSystemIC = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        lblTaiKhoanIC = new javax.swing.JLabel();
        lblTieude = new javax.swing.JLabel();
        pnlLeftBar = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        lblTrangchu = new javax.swing.JLabel();
        pnlBooks = new javax.swing.JPanel();
        lblQLSach = new javax.swing.JLabel();
        pnlAuthors = new javax.swing.JPanel();
        lblQLTacGia = new javax.swing.JLabel();
        pnlRIList = new javax.swing.JPanel();
        lblDSMuonTra = new javax.swing.JLabel();
        pnlGenres = new javax.swing.JPanel();
        lblQLTheLoai = new javax.swing.JLabel();
        lblFeature = new javax.swing.JLabel();
        pnlReader = new javax.swing.JPanel();
        lblQLDocGia = new javax.swing.JLabel();
        pnlBookIssue = new javax.swing.JPanel();
        lblQLMuonSach = new javax.swing.JLabel();
        pnlReturnBook = new javax.swing.JPanel();
        lblTraSach = new javax.swing.JLabel();
        pnlViewReader = new javax.swing.JPanel();
        lblDSDocGia = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống quản lý thư viện");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(205, 193, 255));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSystemIC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystemIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_library_color.png"))); // NOI18N
        pnlHeader.add(lblSystemIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 70));

        lblDangXuat.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_thoat.png"))); // NOI18N
        lblDangXuat.setText("Đăng xuất");
        lblDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
        });
        pnlHeader.add(lblDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 0, 120, 70));

        lblTaiKhoanIC.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTaiKhoanIC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTaiKhoanIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_User.png"))); // NOI18N
        lblTaiKhoanIC.setText(" Admin");
        lblTaiKhoanIC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlHeader.add(lblTaiKhoanIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 220, 70));

        lblTieude.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblTieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieude.setText("Hệ Thống Quản Lý Thư Viện");
        lblTieude.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlHeader.add(lblTieude, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 310, 70));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 70));

        pnlLeftBar.setBackground(new java.awt.Color(0, 0, 0));
        pnlLeftBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHome.setBackground(new java.awt.Color(255, 51, 51));
        pnlHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTrangchu.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblTrangchu.setForeground(new java.awt.Color(255, 255, 255));
        lblTrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_home.png"))); // NOI18N
        lblTrangchu.setText("     Trang chủ");
        pnlHome.add(lblTrangchu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 60));

        pnlLeftBar.add(pnlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 270, 60));

        pnlBooks.setBackground(new java.awt.Color(51, 51, 51));
        pnlBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLSach.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblQLSach.setForeground(new java.awt.Color(255, 255, 255));
        lblQLSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_Book_Shelf.png"))); // NOI18N
        lblQLSach.setText("   Quản lý sách");
        lblQLSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLSachMouseClicked(evt);
            }
        });
        pnlBooks.add(lblQLSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 60));

        pnlLeftBar.add(pnlBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 270, 60));

        pnlAuthors.setBackground(new java.awt.Color(51, 51, 51));
        pnlAuthors.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLTacGia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblQLTacGia.setForeground(new java.awt.Color(255, 255, 255));
        lblQLTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_author.png"))); // NOI18N
        lblQLTacGia.setText("  Quản lý tác giả");
        lblQLTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLTacGiaMouseClicked(evt);
            }
        });
        pnlAuthors.add(lblQLTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 60));

        pnlLeftBar.add(pnlAuthors, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 270, 60));

        pnlRIList.setBackground(new java.awt.Color(51, 51, 51));
        pnlRIList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDSMuonTra.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblDSMuonTra.setForeground(new java.awt.Color(255, 255, 255));
        lblDSMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_team.png"))); // NOI18N
        lblDSMuonTra.setText("   Danh sách mượn trả");
        lblDSMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDSMuonTraMouseClicked(evt);
            }
        });
        pnlRIList.add(lblDSMuonTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 60));

        pnlLeftBar.add(pnlRIList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 270, 60));

        pnlGenres.setBackground(new java.awt.Color(51, 51, 51));
        pnlGenres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLTheLoai.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblQLTheLoai.setForeground(new java.awt.Color(255, 255, 255));
        lblQLTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_muc.png"))); // NOI18N
        lblQLTheLoai.setText("   Quản lý thể loại");
        lblQLTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLTheLoaiMouseClicked(evt);
            }
        });
        pnlGenres.add(lblQLTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 60));

        pnlLeftBar.add(pnlGenres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 60));

        lblFeature.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblFeature.setForeground(new java.awt.Color(255, 255, 255));
        lblFeature.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFeature.setText("Chức năng");
        pnlLeftBar.add(lblFeature, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, 60));

        pnlReader.setBackground(new java.awt.Color(51, 51, 51));
        pnlReader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLDocGia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblQLDocGia.setForeground(new java.awt.Color(255, 255, 255));
        lblQLDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_team.png"))); // NOI18N
        lblQLDocGia.setText("    Quản lý độc giả");
        lblQLDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLDocGiaMouseClicked(evt);
            }
        });
        pnlReader.add(lblQLDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 60));

        pnlLeftBar.add(pnlReader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 270, 60));

        pnlBookIssue.setBackground(new java.awt.Color(51, 51, 51));
        pnlBookIssue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLMuonSach.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblQLMuonSach.setForeground(new java.awt.Color(255, 255, 255));
        lblQLMuonSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_team.png"))); // NOI18N
        lblQLMuonSach.setText("     Sách mượn");
        lblQLMuonSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLMuonSachMouseClicked(evt);
            }
        });
        pnlBookIssue.add(lblQLMuonSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 60));

        pnlLeftBar.add(pnlBookIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 270, 60));

        pnlReturnBook.setBackground(new java.awt.Color(51, 51, 51));
        pnlReturnBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTraSach.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblTraSach.setForeground(new java.awt.Color(255, 255, 255));
        lblTraSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_team.png"))); // NOI18N
        lblTraSach.setText("     Trả lại sách");
        lblTraSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTraSachMouseClicked(evt);
            }
        });
        pnlReturnBook.add(lblTraSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 60));

        pnlLeftBar.add(pnlReturnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 270, 60));

        pnlViewReader.setBackground(new java.awt.Color(51, 51, 51));
        pnlViewReader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDSDocGia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblDSDocGia.setForeground(new java.awt.Color(255, 255, 255));
        lblDSDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_team.png"))); // NOI18N
        lblDSDocGia.setText("     Hồ sơ độc giả");
        lblDSDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDSDocGiaMouseClicked(evt);
            }
        });
        pnlViewReader.add(lblDSDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 60));

        pnlLeftBar.add(pnlViewReader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 270, 60));

        getContentPane().add(pnlLeftBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 850));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Xin chào, Admin");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel12.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Độc giả");
        jPanel13.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_docgia.png"))); // NOI18N
        jLabel21.setText("10   ");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 70));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 240, 140));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_tacgia.png"))); // NOI18N
        jLabel23.setText("10   ");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel14.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 70));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Tác giả");
        jPanel14.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 30));

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 240, 140));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_dausach.png"))); // NOI18N
        jLabel25.setText("10   ");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel15.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, 70));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Đầu sách");
        jPanel15.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 30));

        jPanel12.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 230, 140));

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Lượt mượn");
        jPanel16.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_luotmuon.png"))); // NOI18N
        jLabel28.setText("10   ");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel16.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 70));

        jPanel12.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, 240, 140));

        jScrollPane1.setBackground(new java.awt.Color(255, 153, 153));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đầu sách tiêu biểu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 18))); // NOI18N

        jTable1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tiêu đề", "Tác giả", "Lượt mượn"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setShowGrid(true);
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel12.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 550, 240));

        jScrollPane2.setBackground(new java.awt.Color(255, 153, 153));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Độc giả nổi bật", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 18))); // NOI18N

        jTable2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã độc giả", "Họ và tên", "Lượt mượn", "Email"
            }
        ));
        jTable2.setToolTipText("");
        jTable2.setShowGrid(true);
        jScrollPane2.setViewportView(jTable2);

        jPanel12.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 540, 240));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 1270, 850));

        setSize(new java.awt.Dimension(1534, 916));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        // TODO add your handling code here:
        frmDangnhap login = new frmDangnhap();
        login.setVisible(true);
        // Dong form 
        this.dispose();
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void lblQLTheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLTheLoaiMouseClicked
        // TODO add your handling code here:
        frmQLTheLoai genres = new frmQLTheLoai();
        genres.setVisible(true);
    }//GEN-LAST:event_lblQLTheLoaiMouseClicked

    private void lblQLTacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLTacGiaMouseClicked
        // TODO add your handling code here:
        frmQLTacGia author = new frmQLTacGia();
        author.setVisible(true);
    }//GEN-LAST:event_lblQLTacGiaMouseClicked

    private void lblQLSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLSachMouseClicked
        // TODO add your handling code here:
        frmQLSach book = new frmQLSach();
        book.setVisible(true);
    }//GEN-LAST:event_lblQLSachMouseClicked

    private void lblQLDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLDocGiaMouseClicked
        // TODO add your handling code here:
        frmQLDocGia reader = new frmQLDocGia();
        reader.setVisible(true);
    }//GEN-LAST:event_lblQLDocGiaMouseClicked

    private void lblQLMuonSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLMuonSachMouseClicked
        // TODO add your handling code here:
        frmQLMuonSach issue = new frmQLMuonSach();
        issue.setVisible(true);
    }//GEN-LAST:event_lblQLMuonSachMouseClicked

    private void lblTraSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTraSachMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTraSachMouseClicked

    private void lblDSDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDSDocGiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDSDocGiaMouseClicked

    private void lblDSMuonTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDSMuonTraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDSMuonTraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrangchu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblDSDocGia;
    private javax.swing.JLabel lblDSMuonTra;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblFeature;
    private javax.swing.JLabel lblQLDocGia;
    private javax.swing.JLabel lblQLMuonSach;
    private javax.swing.JLabel lblQLSach;
    private javax.swing.JLabel lblQLTacGia;
    private javax.swing.JLabel lblQLTheLoai;
    private javax.swing.JLabel lblSystemIC;
    private javax.swing.JLabel lblTaiKhoanIC;
    private javax.swing.JLabel lblTieude;
    private javax.swing.JLabel lblTraSach;
    private javax.swing.JLabel lblTrangchu;
    private javax.swing.JPanel pnlAuthors;
    private javax.swing.JPanel pnlBookIssue;
    private javax.swing.JPanel pnlBooks;
    private javax.swing.JPanel pnlGenres;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlLeftBar;
    private javax.swing.JPanel pnlRIList;
    private javax.swing.JPanel pnlReader;
    private javax.swing.JPanel pnlReturnBook;
    private javax.swing.JPanel pnlViewReader;
    // End of variables declaration//GEN-END:variables
}
