/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui_library;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class frmUserHome extends javax.swing.JFrame {

    /**
     * Creates new form frmUserHome
     */
    public frmUserHome() {
        initComponents();
        // can giua form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeftBar = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        lblTrangchu = new javax.swing.JLabel();
        pnlBooks = new javax.swing.JPanel();
        btnQLSach = new javax.swing.JButton();
        pnlAuthors = new javax.swing.JPanel();
        btnQLTacGia = new javax.swing.JButton();
        pnlGenres = new javax.swing.JPanel();
        btnQLTheLoai = new javax.swing.JButton();
        lblFeature = new javax.swing.JLabel();
        pnlBookIssue = new javax.swing.JPanel();
        btnQLMuonSach = new javax.swing.JButton();
        pnlViewReader = new javax.swing.JPanel();
        btnDSDocGia = new javax.swing.JButton();
        pnlRIList1 = new javax.swing.JPanel();
        btnDSMuonTra1 = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        lblSystemIC = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        lblTaiKhoanIC = new javax.swing.JLabel();
        lblTieude = new javax.swing.JLabel();
        pnlSystem = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeftBar.setBackground(new java.awt.Color(213, 184, 255));
        pnlLeftBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 0, new java.awt.Color(90, 34, 139)));
        pnlLeftBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHome.setBackground(new java.awt.Color(159, 90, 253));
        pnlHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTrangchu.setBackground(new java.awt.Color(255, 255, 255));
        lblTrangchu.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTrangchu.setForeground(new java.awt.Color(255, 255, 255));
        lblTrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_home.png"))); // NOI18N
        lblTrangchu.setText("     Trang chủ");
        lblTrangchu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHome.add(lblTrangchu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 220, 60));

        pnlLeftBar.add(pnlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 42, 266, 60));

        pnlBooks.setBackground(new java.awt.Color(241, 231, 254));
        pnlBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQLSach.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnQLSach.setForeground(new java.awt.Color(90, 34, 139));
        btnQLSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_sach.png"))); // NOI18N
        btnQLSach.setText("    Kho sách");
        btnQLSach.setContentAreaFilled(false);
        btnQLSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQLSach.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLSachMouseClicked(evt);
            }
        });
        pnlBooks.add(btnQLSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 60));

        pnlLeftBar.add(pnlBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 280, 266, 60));

        pnlAuthors.setBackground(new java.awt.Color(241, 231, 254));
        pnlAuthors.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQLTacGia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnQLTacGia.setForeground(new java.awt.Color(90, 34, 139));
        btnQLTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_author.png"))); // NOI18N
        btnQLTacGia.setText("    Tác giả");
        btnQLTacGia.setContentAreaFilled(false);
        btnQLTacGia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLTacGia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQLTacGia.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLTacGiaMouseClicked(evt);
            }
        });
        pnlAuthors.add(btnQLTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 60));

        pnlLeftBar.add(pnlAuthors, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 220, 266, 60));

        pnlGenres.setBackground(new java.awt.Color(241, 231, 254));
        pnlGenres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQLTheLoai.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnQLTheLoai.setForeground(new java.awt.Color(90, 34, 139));
        btnQLTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_muc.png"))); // NOI18N
        btnQLTheLoai.setText("    Thế loại");
        btnQLTheLoai.setContentAreaFilled(false);
        btnQLTheLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLTheLoai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQLTheLoai.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLTheLoaiMouseClicked(evt);
            }
        });
        pnlGenres.add(btnQLTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 60));

        pnlLeftBar.add(pnlGenres, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 160, 266, 60));

        lblFeature.setBackground(new java.awt.Color(102, 51, 153));
        lblFeature.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        lblFeature.setForeground(new java.awt.Color(102, 51, 153));
        lblFeature.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFeature.setText("Chức năng");
        pnlLeftBar.add(lblFeature, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 40));

        pnlBookIssue.setBackground(new java.awt.Color(241, 231, 254));
        pnlBookIssue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQLMuonSach.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnQLMuonSach.setForeground(new java.awt.Color(90, 34, 139));
        btnQLMuonSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_muons.png"))); // NOI18N
        btnQLMuonSach.setText("    Đăng kí mượn");
        btnQLMuonSach.setContentAreaFilled(false);
        btnQLMuonSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLMuonSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQLMuonSach.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLMuonSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLMuonSachMouseClicked(evt);
            }
        });
        pnlBookIssue.add(btnQLMuonSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 60));

        pnlLeftBar.add(pnlBookIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 340, 266, 60));

        pnlViewReader.setBackground(new java.awt.Color(241, 231, 254));
        pnlViewReader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDSDocGia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnDSDocGia.setForeground(new java.awt.Color(90, 34, 139));
        btnDSDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_profile.png"))); // NOI18N
        btnDSDocGia.setText("    Hồ sơ ");
        btnDSDocGia.setContentAreaFilled(false);
        btnDSDocGia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDSDocGia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDSDocGia.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDSDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDSDocGiaMouseClicked(evt);
            }
        });
        pnlViewReader.add(btnDSDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 60));

        pnlLeftBar.add(pnlViewReader, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 460, 266, 60));

        pnlRIList1.setBackground(new java.awt.Color(241, 231, 254));
        pnlRIList1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDSMuonTra1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnDSMuonTra1.setForeground(new java.awt.Color(90, 34, 139));
        btnDSMuonTra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_DsChiTiet.png"))); // NOI18N
        btnDSMuonTra1.setText("    Danh sách mượn");
        btnDSMuonTra1.setContentAreaFilled(false);
        btnDSMuonTra1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDSMuonTra1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDSMuonTra1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDSMuonTra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDSMuonTra1MouseClicked(evt);
            }
        });
        pnlRIList1.add(btnDSMuonTra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 60));

        pnlLeftBar.add(pnlRIList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 400, 266, 60));

        getContentPane().add(pnlLeftBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 840));

        pnlHeader.setBackground(new java.awt.Color(90, 34, 139));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSystemIC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystemIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_library_color.png"))); // NOI18N
        pnlHeader.add(lblSystemIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 70));

        lblDangXuat.setBackground(new java.awt.Color(241, 231, 254));
        lblDangXuat.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_exit_color.png"))); // NOI18N
        lblDangXuat.setText("  Đăng xuất");
        lblDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
        });
        pnlHeader.add(lblDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, 120, 70));

        lblTaiKhoanIC.setBackground(new java.awt.Color(241, 231, 254));
        lblTaiKhoanIC.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTaiKhoanIC.setForeground(new java.awt.Color(255, 255, 255));
        lblTaiKhoanIC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTaiKhoanIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_User.png"))); // NOI18N
        lblTaiKhoanIC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlHeader.add(lblTaiKhoanIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 220, 70));

        lblTieude.setBackground(new java.awt.Color(241, 231, 254));
        lblTieude.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblTieude.setForeground(new java.awt.Color(255, 255, 255));
        lblTieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieude.setText("Thư Viện Tri Thức");
        lblTieude.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlHeader.add(lblTieude, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 310, 70));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 70));

        pnlSystem.setBackground(new java.awt.Color(255, 255, 255));
        pnlSystem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(90, 34, 139)));
        pnlSystem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(90, 34, 139));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Xin chào");
        lblWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlSystem.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        getContentPane().add(pnlSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 1270, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLSachMouseClicked
        try {
            // TODO add your handling code here:
            QLSach book = new QLSach(this, true);
            book.setVisible(true);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(frmTrangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQLSachMouseClicked

    private void btnQLTacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLTacGiaMouseClicked
        
        try {
            // TODO add your handling code here:
            QLTacGia author = new QLTacGia(this, true);
            author.setVisible(true); // Hiển thị form
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(frmUserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnQLTacGiaMouseClicked

    private void btnQLTheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLTheLoaiMouseClicked
        try {
            // TODO add your handling code here:
            
            QLTheLoai genres = new QLTheLoai(this, true); // Truyền JFrame cha và chế độ modal
            genres.setVisible(true);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(frmUserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnQLTheLoaiMouseClicked

    private void btnQLMuonSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLMuonSachMouseClicked
        try {
            // TODO add your handling code here:
            QLMuonSach issue = new QLMuonSach(this, true);
            issue.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmUserHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQLMuonSachMouseClicked

    private void btnDSDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDSDocGiaMouseClicked
        // TODO add your handling code here:
        DSDocGia lstreader = new DSDocGia(this, true);
        lstreader.setVisible(true);
    }//GEN-LAST:event_btnDSDocGiaMouseClicked

    private void btnDSMuonTra1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDSMuonTra1MouseClicked
        // TODO add your handling code here:
        DSMuonTra lstRI = new DSMuonTra(this, true);
        lstRI.setVisible(true);
    }//GEN-LAST:event_btnDSMuonTra1MouseClicked

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, "Bạn có muốn rời khỏi hệ thống?", "Xác Nhận Đăng Xuất", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
            try {
                // Quay về màn hình đăng nhập // Đóng màn hình chính }
                frmDangnhap login = new frmDangnhap();
                login.setVisible(true);
                // Dong form
                this.dispose();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(frmUserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblDangXuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmUserHome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDSDocGia;
    private javax.swing.JButton btnDSMuonTra1;
    private javax.swing.JButton btnQLMuonSach;
    private javax.swing.JButton btnQLSach;
    private javax.swing.JButton btnQLTacGia;
    private javax.swing.JButton btnQLTheLoai;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblFeature;
    private javax.swing.JLabel lblSystemIC;
    private javax.swing.JLabel lblTaiKhoanIC;
    private javax.swing.JLabel lblTieude;
    private javax.swing.JLabel lblTrangchu;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlAuthors;
    private javax.swing.JPanel pnlBookIssue;
    private javax.swing.JPanel pnlBooks;
    private javax.swing.JPanel pnlGenres;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlLeftBar;
    private javax.swing.JPanel pnlRIList1;
    private javax.swing.JPanel pnlSystem;
    private javax.swing.JPanel pnlViewReader;
    // End of variables declaration//GEN-END:variables
}
